const SUPABASE_URL = "https://ytdzvybgvxbbxttpgaho.supabase.co";
const SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl0ZHp2eWJndnhiYnh0dHBnYWhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI0OTE5NTAsImV4cCI6MjA4ODA2Nzk1MH0.xoQjf8CIGHEmFlKrfhsjulrfRS7U2wrjTDXFpooYTvc";
const supabaseClient = supabase.createClient(SUPABASE_URL, SUPABASE_KEY);

window.supabaseClient = supabaseClient;
